services:
  postgres:
    container_name: postgres_street_scout
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#  backend:
#    image: macchiato23/street-scout-be:latest
#    container_name: street_scout_backend
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=test
#    networks:
#      - postgres
#    depends_on:
#      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: