server:
  port: 8080

spring:
  application:
    name: street-scout
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

aws:
  s3:
    access:
      key: ${AWS_ACCESS_KEY_ID}
    secret:
      key: ${AWS_SECRET_ACCESS_KEY}
    bucket:
      name: ${AWS_S3_BUCKET_NAME}
