spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:street_scout}
    password: ${DATABASE_PASSWORD:password}
    username: ${DATABASE_USER:default}